# docker-compose.fe.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tuyen_frontend_prod
    environment:
      # ชี้ NEXT_PUBLIC_API_URL ไปที่ IP หรือ โดเมน ของเครื่อง EC2 Backend ของคุณ
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "80:3000"
    restart: always
