# docker-compose.be.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tuyen_backend_prod
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SPOONACULAR_API_KEY=${SPOONACULAR_API_KEY}
      # ชี้ AI_SERVICE_URL ไปที่ IP ของเครื่อง EC2 AI Service
      - AI_SERVICE_URL=${AI_SERVICE_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - "80:8000" # เปิดสิทธิ์พอร์ต 80 เพื่อใช้เป็น Public API เข้าเครื่องได้ทันที
    restart: always
    networks:
      - tuyen_network

networks:
  tuyen_network:
    driver: bridge
